website/models.py
from flask_login import UserMixin
from extension import db


# Table for many to many relationship of student table and course table
class Enrolled(db.Model):
    __tablename__ = "student_enrolled"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey('student.id'), nullable=False)
    course_id =  db.Column(db.Integer, db.ForeignKey('course.id'), nullable=False)
    session_id = db.Column(db.Integer, db.ForeignKey('session.id'), nullable=False)

    __table_args__ = (db.UniqueConstraint(student_id, course_id, session_id),)

    student = db.relationship('Student', back_populates='student_enrolled', passive_deletes='all')
    course = db.relationship('Course', back_populates='course_enrolled', passive_deletes='all')
    session = db.relationship('Session', back_populates='session_enrolled', passive_deletes='all')


class Student(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True)
    student_name = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(250))
    student_enrolled = db.relationship('Enrolled', cascade="all,delete", back_populates='student')

    
class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(80), nullable=False)
    credit_score = db.Column(db.Integer, nullable=False, default=0)
    code = db.Column(db.Integer, nullable=False, default=0)
    course_enrolled = db.relationship('Enrolled', back_populates='course')
    
    def __repr__(self):
        return self.subject

# One to many relation of course table to session table
class Session(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    datetime = db.Column(db.String(50), nullable=False)
    classroom = db.Column(db.String(50), nullable=False)
    course_id = db.Column(db.Integer, db.ForeignKey('course.id'))
    session_enrolled = db.relationship('Enrolled', back_populates='session')

website/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, ValidationError
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.validators import InputRequired, Email, Length

from models import Course, Session, Student

class Login(FlaskForm):
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=15)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('remember me')

class RegistrationForm(FlaskForm):
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=15)])
    student_name = StringField('name', validators=[InputRequired()])
    email = StringField('email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])

    def validate_email(self, email):
        if Student.query.filter_by(email=email.data).first():
            raise ValidationError("Email already registered!")

    def validate_username(self, username):
        if Student.query.filter_by(username=username.data).first():
            raise ValidationError("Username already taken! Please try a different username.")


def choice_query_option():
    return Course.query

def choice_query_datetime():
    return Session.query

class ChoiceForm(FlaskForm):
    option = QuerySelectField(query_factory=choice_query_option, allow_blank=True, get_label='subject')
    timeslot = QuerySelectField(query_factory=choice_query_datetime, allow_blank=True, get_label='datetime')

website/__init__.py
import os, sys; sys.path.append(os.path.dirname(os.path.realpath(__file__)))

website/app.py
from flask import Flask

import admins
from extension import db, admin, login_manager, migrate, Bootstrap
from auth import bp
from views import bp2



def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)
    
    db.init_app(app)
    admin.init_app(app, index_view=admins.MyAdminHomeView())
    migrate.init_app(app, db)
    login_manager.init_app(app)
    Bootstrap.init_app(app)

    app.register_blueprint(bp)
    app.register_blueprint(bp2)
    
    return app
    

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

from models import Student
from extension import db, login_manager
from forms import Login, RegistrationForm


bp = Blueprint('auth', __name__)
login_manager.login_view = 'login'
@login_manager.user_loader
def load_user(user_id):
    return Student.query.get(user_id)

import app

@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = Login()

    if form.validate_on_submit():
        user = Student.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                flash('Login success.')
                return redirect(url_for('view.get_data'))        
        flash('Invalid username or password')
        return redirect(url_for('auth.login'))


    return render_template('login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have logged out!')
    return redirect(url_for('auth.login'))




@bp.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = Student(username=form.username.data, student_name=form.student_name.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        flash('Registration completed. Please sign in.')
        return redirect(url_for('auth.login')) 

    return render_template('signup.html', form=form)


@bp.route('/admin')
def admin():
    return render_template('admin/index.html')

@bp.route('/admin2')
def admin_access():
    return render_template('admin/index_access.html')

website/views.py
from flask import Blueprint, flash, render_template, redirect, url_for, request, jsonify
import flask_login

from models import Course, Session, Student, Enrolled
from forms import ChoiceForm
from extension import db


bp2 = Blueprint('view', __name__)

@bp2.route('/user', methods=['GET', 'POST'])
def get_data():
    form = ChoiceForm()
    user = flask_login.current_user
    get_student = user.student_enrolled

    x_list = []
    for subject in get_student:
        subjects = subject.course
        x_list.append(subjects)

    course_list = Course.query.all()
    get_course = []
    for course in course_list:
        subjects = course
        get_course.append(subjects)


    form.option.query = []
    for subject in get_course:
        if subject not in x_list:
            form.option.query.append(subject)


    if form.validate_on_submit():
        register_subject = Enrolled(student=user, course=form.option.data, session=form.timeslot.data)

        db.session.add(register_subject)
        db.session.commit()
        flash(f'The subject {form.option.data} has been registered!')
        return redirect(url_for('view.get_data'))

    return render_template('user.html', form=form, registered=get_student, user=user)


@bp2.route('/<int:cid>/<int:sid>/delete', methods=['GET', 'POST'])
def delete(cid, sid):
    user = flask_login.current_user
    schedule = Enrolled.query.filter_by(student_id=user.id).filter_by(course_id=cid).filter_by(session_id=sid)

    if request.method == "POST":
        schedule.delete()
        db.session.commit()

        flash(f'Subject select has been deleted.')
        return redirect(url_for('view.get_data'))
    
    return render_template('delete.html')


@bp2.route('/session/<id>')
def session(id):
    schedule = db.session.query(Session.id, Session.datetime).join(Course).filter(Course.id == id).all()

    sessionArray = []

    for ses in schedule:
        sesObj = {}
        sesObj['id'] = ses.id
        sesObj['datetime'] = ses.datetime
        sessionArray.append(sesObj)

    return jsonify({'slot': sessionArray})

website/templates/base.html
{% extends "bootstrap/base.html" %}
{% include "header.html" %}

<title>{% block title %} Flask CRUD {% endblock %}</title>

{% block head %}
{{super()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
{% endblock %}}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='starter-template.css')}}">
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <center>{{ message }}</center>
    {% endfor %}
  {% endif %}
{% endwith %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Student Course Registrar</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.sign_up') }}">Sign Up</a></li>
            <li><a href="{{ url_for('auth.admin') }}">Admin</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}

website/templates/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
 
 
 
{% block title %} Delete {% endblock %}
 
 
 
{% block body %}
<div class="container">
<form action='' method="post">
    Click YES to confirm
    <input type = "submit" value="YES" class="btn btn-danger">
    <a href='/user'>Cancel</a>
</form>
</div>
{% endblock %}

website/templates/header.html
{% block body %}
<div class="jumbotron p-3">
    <div class="well text-center">
        <h1>Python Flask CRUD Web Application Development </h1>
    </div>
</div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block head %}
{{super()}}
{% endblock %}

{% block title %}
Home Page
{% endblock %}

{% block content %}
{{super()}}
<div class="container">

  <br class="starter-template">
    <h1></h1>
    <p class="lead"></p>
  </div>
{% endblock %}
</div><!-- /.container -->

website/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login {% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/signin.css')}}">
{% endblock %}

{% block content %}
{{super()}}
    <div class="container">

      <form class="form-signin" method="POST" action="/login">
        <br></br>
        <h2 class="form-signin-heading">Please sign in</h2>

        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.username) }}
        {{ wtf.form_field(form.password) }}
        {{ wtf.form_field(form.remember) }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
    </div> <!-- /container -->
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/signin.css')}}">
{% endblock %}

{% block content %}
{{super()}}
<div class="container">

  <form class="form-signin" method="POST" action="/sign-up">
    <h2 class="form-signin-heading">Sign Up</h2>
    {{ form.hidden_tag() }}
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.student_name) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
  </form>

</div> <!-- /container -->
{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}
User
{% endblock %}

{% block styles %}
{{super.super()}}
  <link rel="stylesheet" href="{{url_for('static', filename='css/signin.css')}}">
{% endblock %}

{% block content %}
{{super()}}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Student Course Registrar</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{ url_for('view.get_data') }}">Home</a></li>
        <li><a href="{{ url_for('auth.admin') }}">Admin</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
    <div class="container">
      <h1 align="center">Welcome {{user.student_name}}!</h1>
    </div>
    <div class="container">
    <div>
      <table class="table">
        <thead style="background-color: brown;color: aliceblue;">
          <th>Subject Code</th>
          <th>Subject Registered</th>
          <th>Credit</th>
          <th>Session</th>
          <th>Action</th>
        </thead>
        <tbody>
          {% for user in registered %}
          <tr>
            <td>{{ user.course.code }}</td>
            <td>{{ user.course.subject }}</td>
            <td>{{ user.course.credit_score }}</td>
            <td>{{ user.session.datetime }}</td>
            <td>
              <span style="font-size: 24px;color:red;">
              <a href="/{{user.course_id}}/{{user.session_id}}/delete">  <i class="fas fa-trash-alt"></i></a></span>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
      <form class="form-signin" method="POST" action="/user">
        <h2 class="form-signin-heading">Select a subject to register</h2>
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.option) }}
        {{ wtf.form_field(form.timeslot) }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      </form>
      <script>
        let subject_select = document.getElementById('option');
        let datetime_select = document.getElementById('timeslot');

        subject_select.onchange = function() {
          subject = subject_select.value;

          fetch('/session/' + subject).then(function(response) {
            
            response.json().then(function(data) {
              let optionHTML = ''

              for (let session of data.slot) {
                optionHTML += '<option value="' + session.id + '">' + session.datetime + '</option>'
              }

              datetime_select.innerHTML = optionHTML

            });
          });
        }
      </script>

    </div> <!-- /container -->
{% endblock %}